// AUTO-GENERATED by scripts/gen-english-meta.mjs — DO NOT EDIT BY HAND.
// Slim meta-only index of the English article library (no article bodies) so
// consumers like the internal student page don't bundle ~11MB of full articles.
// Regenerate after adding articles:  npm run gen-english-meta

export interface EnglishArticleMeta {
  slug: string;
  title: string;
  titleZh: string;
  cefr: string;
  words: number;
  minutes: number;
}

export const englishArticleMeta: EnglishArticleMeta[] = [
  {
    "slug": "2026-05-09",
    "title": "The Throne Changes Hands: What Alcaraz's Wimbledon Repeat Means for Men's Tennis",
    "titleZh": "王座易主：男子网球的新时代",
    "cefr": "B2",
    "words": 393,
    "minutes": 5
  },
  {
    "slug": "2026-05-08",
    "title": "A 21-Year-Old From Murcia and the Lawn He Refused to Give Back",
    "titleZh": "阿尔卡拉斯再次守住了温网草地",
    "cefr": "B1",
    "words": 273,
    "minutes": 4
  },
  {
    "slug": "2026-05-07",
    "title": "A Frame, a Myth, a Memo: What Butler Left Behind",
    "titleZh": "Butler留下的三件遗物",
    "cefr": "C2",
    "words": 528,
    "minutes": 7
  },
  {
    "slug": "2026-05-06",
    "title": "The Frame That Survived: Butler, the Roof, and the Image That Followed",
    "titleZh": "宾州屋顶、那张照片与那个空位",
    "cefr": "C1",
    "words": 477,
    "minutes": 6
  },
  {
    "slug": "2026-05-05",
    "title": "A Wet, Bouncy Calf and the Strange Economics of Going Viral",
    "titleZh": "小河马与病毒传播的经济学",
    "cefr": "B2",
    "words": 408,
    "minutes": 5
  },
  {
    "slug": "2026-05-04",
    "title": "The Baby Hippo Who Outran Her Own Zoo",
    "titleZh": "那只小河马超越了她的动物园",
    "cefr": "B1",
    "words": 297,
    "minutes": 4
  },
  {
    "slug": "2026-05-03",
    "title": "The Broken Compact: What China's Graduates Inherit When the Diploma's Promise Fails",
    "titleZh": "文凭的承诺失效之后",
    "cefr": "C2",
    "words": 524,
    "minutes": 7
  },
  {
    "slug": "2026-05-02",
    "title": "A Quieter Number, the Same Long Queue: China's Graduates and the Office Jobs That Did Not Wait",
    "titleZh": "毕业生与等不来的白领职位",
    "cefr": "C1",
    "words": 458,
    "minutes": 6
  },
  {
    "slug": "2026-05-01",
    "title": "The Deal That Settled Nothing",
    "titleZh": "那桩和解什么也没有解决",
    "cefr": "C2",
    "words": 528,
    "minutes": 7
  },
  {
    "slug": "2026-04-30",
    "title": "Free, but at What Cost: The Assange Plea and Its Unfinished Questions",
    "titleZh": "阿桑奇自由了，新闻自由呢",
    "cefr": "C1",
    "words": 456,
    "minutes": 6
  },
  {
    "slug": "2026-04-29",
    "title": "A Voice From the Edge: How a Forty-Seven-Year-Old Machine Came Back On Speaking Terms",
    "titleZh": "旅行者1号从宇宙边缘回话了",
    "cefr": "C2",
    "words": 528,
    "minutes": 7
  },
  {
    "slug": "2026-04-28",
    "title": "A Dying Chip, a 45-Year-Old Computer, and the Longest Repair Call in History",
    "titleZh": "一颗坏芯片与45年后的维修",
    "cefr": "C1",
    "words": 451,
    "minutes": 6
  },
  {
    "slug": "2026-04-27",
    "title": "On-Device, On-Brand: What Apple Intelligence Actually Sells",
    "titleZh": "端侧处理与苹果的平台层主张",
    "cefr": "C2",
    "words": 404,
    "minutes": 6
  },
  {
    "slug": "2026-04-26",
    "title": "The Privacy Pitch Apple Built Before It Had a Product to Match It",
    "titleZh": "苹果先建好隐私叙事再补产品",
    "cefr": "C1",
    "words": 472,
    "minutes": 6
  },
  {
    "slug": "2026-04-25",
    "title": "A Month of Football Germany Was Quietly Ready For",
    "titleZh": "德国举办了一届有秩序的欧洲杯",
    "cefr": "B2",
    "words": 401,
    "minutes": 5
  },
  {
    "slug": "2026-04-24",
    "title": "The Quiet Way Spain Won Euro 2024",
    "titleZh": "西班牙安静地赢得了欧洲杯",
    "cefr": "B1",
    "words": 255,
    "minutes": 4
  },
  {
    "slug": "2026-04-23",
    "title": "Banner Eighteen, and a League That Will Not Let Anyone Hold It Twice",
    "titleZh": "第18面旗帜与六年六支冠军",
    "cefr": "B2",
    "words": 405,
    "minutes": 5
  },
  {
    "slug": "2026-04-22",
    "title": "How Boston Lifted Banner Eighteen and Sent the Lakers Home",
    "titleZh": "凯尔特人挂上了第18面冠军旗",
    "cefr": "B1",
    "words": 318,
    "minutes": 4
  },
  {
    "slug": "2026-04-21",
    "title": "A Liturgy on the Limestone: What the Apulia G7 Was Really For",
    "titleZh": "阿普利亚峰会是在演什么",
    "cefr": "C2",
    "words": 529,
    "minutes": 7
  },
  {
    "slug": "2026-04-20",
    "title": "A Loan Backed by Frozen Money, and a Pope Talking About Machines",
    "titleZh": "冻结资产的贷款与教皇谈AI",
    "cefr": "C1",
    "words": 423,
    "minutes": 6
  },
  {
    "slug": "2026-04-19",
    "title": "A Vote Few Took as Final, and the President Who Did",
    "titleZh": "极右翼的票与把它当结论的人",
    "cefr": "C2",
    "words": 464,
    "minutes": 6
  },
  {
    "slug": "2026-04-18",
    "title": "The Night the Map Tilted: How One European Vote Pushed a President to Gamble",
    "titleZh": "欧选结果把法国总统逼上赌桌",
    "cefr": "C1",
    "words": 462,
    "minutes": 6
  },
  {
    "slug": "2026-04-17",
    "title": "The Word That Did Not Quite Fit: Starliner, Two Astronauts, and a Company in Slow Retreat",
    "titleZh": "「被困」这个词并不完全准确",
    "cefr": "C2",
    "words": 492,
    "minutes": 7
  },
  {
    "slug": "2026-04-16",
    "title": "An Eight-Day Test Flight That Quietly Became 286 Days",
    "titleZh": "八天测试变成了286天滞留",
    "cefr": "C1",
    "words": 413,
    "minutes": 6
  },
  {
    "slug": "2026-04-15",
    "title": "A Physicist, a Supermajority, and the Country She Inherits",
    "titleZh": "一位物理学家赢得超级多数席",
    "cefr": "C2",
    "words": 439,
    "minutes": 7
  },
  {
    "slug": "2026-04-14",
    "title": "A Climate Scientist Inherits a Country, and the Sentence That Came With It",
    "titleZh": "一位气候科学家当选了总统",
    "cefr": "C1",
    "words": 454,
    "minutes": 6
  },
  {
    "slug": "2026-04-13",
    "title": "A Few Hours at the Top: When a Chip Designer Briefly Out-Weighed Apple",
    "titleZh": "一家芯片公司短暂超越了苹果",
    "cefr": "C2",
    "words": 438,
    "minutes": 7
  },
  {
    "slug": "2026-04-12",
    "title": "For an Afternoon, the World's Biggest Company Made Graphics Chips",
    "titleZh": "那个下午，英伟达短暂登顶",
    "cefr": "C1",
    "words": 478,
    "minutes": 6
  },
  {
    "slug": "2026-04-11",
    "title": "A Verdict That Disqualifies Nobody: The Constitutional Novelty of a Felonious Candidate",
    "titleZh": "定罪了他，却无法取消资格",
    "cefr": "C2",
    "words": 539,
    "minutes": 7
  },
  {
    "slug": "2026-04-10",
    "title": "A Paperwork Crime That Quietly Rewrote a Sentence in the Constitution",
    "titleZh": "一桩账册罪写进了宪法先例",
    "cefr": "C1",
    "words": 432,
    "minutes": 6
  },
  {
    "slug": "2026-04-09",
    "title": "Why a Brooklyn Comedy Outflanked the Auteurs at Cannes",
    "titleZh": "小成本喜剧如何击败大导演",
    "cefr": "B2",
    "words": 417,
    "minutes": 5
  },
  {
    "slug": "2026-04-08",
    "title": "A Brooklyn Stripper Story Just Won Cannes' Top Prize",
    "titleZh": "布鲁克林喜剧拿走了金棕榈",
    "cefr": "B1",
    "words": 313,
    "minutes": 4
  },
  {
    "slug": "2026-04-07",
    "title": "Cannes Opens, and the Air Is Heavier Than the Carpet",
    "titleZh": "戛纳开幕了，空气比红毯更沉",
    "cefr": "B2",
    "words": 405,
    "minutes": 5
  },
  {
    "slug": "2026-04-06",
    "title": "How a Four-Part Comedy and Greta Gerwig Opened the 77th Cannes",
    "titleZh": "葛韦格主持了戛纳77的开幕",
    "cefr": "B1",
    "words": 305,
    "minutes": 4
  },
  {
    "slug": "2026-04-05",
    "title": "A Handful of the Other Side: What Chang'e 6 Actually Brought Back",
    "titleZh": "嫦娥六号带回了月背土壤",
    "cefr": "C2",
    "words": 539,
    "minutes": 7
  },
  {
    "slug": "2026-04-04",
    "title": "The Quiet Hemisphere Finally Speaks",
    "titleZh": "月球背面第一批土样",
    "cefr": "C1",
    "words": 407,
    "minutes": 6
  },
  {
    "slug": "2026-04-03",
    "title": "A Helicopter, a Hidden Question, and What Iran's Snap Election Was Quietly Asking",
    "titleZh": "一架直升机与伊朗的静悄悄大选",
    "cefr": "C2",
    "words": 495,
    "minutes": 7
  },
  {
    "slug": "2026-04-02",
    "title": "A Helicopter, a Fog Bank, and the Office That Kept Functioning",
    "titleZh": "直升机坠雾，政府运转如常",
    "cefr": "C1",
    "words": 472,
    "minutes": 6
  },
  {
    "slug": "2026-04-01",
    "title": "A Bridge in the Weights: What Golden Gate Claude Was Actually Showing Us",
    "titleZh": "金门大桥嵌在模型权重里",
    "cefr": "C2",
    "words": 510,
    "minutes": 7
  },
  {
    "slug": "2026-03-31",
    "title": "The Day a Chatbot Could Not Stop Talking About a Bridge",
    "titleZh": "那天聊天机器人只谈一座桥",
    "cefr": "C1",
    "words": 418,
    "minutes": 6
  },
  {
    "slug": "2026-03-30",
    "title": "The Voice Was the Whole Argument",
    "titleZh": "声音是整个争议的核心",
    "cefr": "C2",
    "words": 521,
    "minutes": 7
  },
  {
    "slug": "2026-03-29",
    "title": "A Voice That Sounded Like Hers, and the Week That Followed",
    "titleZh": "那个声音引发了一周争议",
    "cefr": "C1",
    "words": 394,
    "minutes": 6
  },
  {
    "slug": "2026-03-28",
    "title": "A Eurovision Won by the Juries While the Streets Argued Outside",
    "titleZh": "评审团赢了，街道上还在争论",
    "cefr": "B2",
    "words": 349,
    "minutes": 5
  },
  {
    "slug": "2026-03-27",
    "title": "The Singer Who Broke the Code, and the Trophy",
    "titleZh": "瑞士歌手打破规则，拿走奖杯",
    "cefr": "B1",
    "words": 261,
    "minutes": 4
  },
  {
    "slug": "2026-03-26",
    "title": "A Word the Continent Had Stopped Using: The Fico Shooting and the Floor of Polarized Politics",
    "titleZh": "欧洲已经很久没用过那个词了",
    "cefr": "C2",
    "words": 539,
    "minutes": 7
  },
  {
    "slug": "2026-03-25",
    "title": "How a Retired Poet Came to Believe Disagreement No Longer Travelled: The Fico Shooting in Context",
    "titleZh": "那位诗人相信正常异议已失效",
    "cefr": "C1",
    "words": 419,
    "minutes": 6
  },
  {
    "slug": "2026-03-24",
    "title": "Eleven Minutes for a Nose: What the 150th Derby Asked of Its Winners",
    "titleZh": "两分钟比赛，十一分钟等结果",
    "cefr": "B2",
    "words": 366,
    "minutes": 5
  },
  {
    "slug": "2026-03-23",
    "title": "A Horse, the Rail, and a Nose: How Mystik Dan Won the 150th Derby",
    "titleZh": "鼻尖之差与第150届肯塔基赛",
    "cefr": "B1",
    "words": 319,
    "minutes": 4
  },
  {
    "slug": "2026-03-22",
    "title": "A Long Argument Conducted in Photons",
    "titleZh": "用光子进行的漫长争论",
    "cefr": "C2",
    "words": 495,
    "minutes": 7
  },
  {
    "slug": "2026-03-21",
    "title": "The Telescope That Refused to Hand Over the Sky",
    "titleZh": "哈勃拒绝把天空让给继任者",
    "cefr": "C1",
    "words": 438,
    "minutes": 6
  },
  {
    "slug": "2026-03-20",
    "title": "How a Rap Feud Compressed Itself into a Single Weekend",
    "titleZh": "说唱对决压缩进了一个周末",
    "cefr": "B2",
    "words": 372,
    "minutes": 5
  },
  {
    "slug": "2026-03-19",
    "title": "How a Drake Diss Track Turned Into a Crowd Anthem in Six Weeks",
    "titleZh": "一首diss如何在六周变成合唱",
    "cefr": "B1",
    "words": 277,
    "minutes": 4
  },
  {
    "slug": "2026-03-18",
    "title": "How a Bag Charm Pulled an Entire Supply Chain Out of Beijing",
    "titleZh": "一个挂件拉动了整条供应链",
    "cefr": "B2",
    "words": 392,
    "minutes": 5
  },
  {
    "slug": "2026-03-17",
    "title": "How a Pop Star Made a Tiny Monster Famous",
    "titleZh": "一位歌手让玩具怪兽出名了",
    "cefr": "B1",
    "words": 310,
    "minutes": 4
  },
  {
    "slug": "2026-03-16",
    "title": "When the Last Line of Defense Goes Public",
    "titleZh": "勒索软件时代的数据安全上市",
    "cefr": "C1",
    "words": 451,
    "minutes": 6
  },
  {
    "slug": "2026-03-15",
    "title": "A Backup Company Walks Into Wall Street, and the Lights Come Back On",
    "titleZh": "备份公司上市，科技IPO重启",
    "cefr": "B2",
    "words": 420,
    "minutes": 5
  },
  {
    "slug": "2026-03-14",
    "title": "The Twenty-Six Days, and What They Showed About a Borrowed Office",
    "titleZh": "二十六天与「借来的职位」",
    "cefr": "C2",
    "words": 646,
    "minutes": 8
  },
  {
    "slug": "2026-03-13",
    "title": "The Twenty-Four Days Between a Debate and a Tweet",
    "titleZh": "辩论与退选推文之间的24天",
    "cefr": "C1",
    "words": 501,
    "minutes": 6
  },
  {
    "slug": "2026-03-12",
    "title": "A Calendar Built Out of Code, and the Industry It Has Quietly Reshaped",
    "titleZh": "嵌在代码里的四年时钟",
    "cefr": "C1",
    "words": 577,
    "minutes": 6
  },
  {
    "slug": "2026-03-11",
    "title": "The Night Bitcoin Halved Its Own Paycheck",
    "titleZh": "比特币把自己的工资砍了一半",
    "cefr": "B2",
    "words": 411,
    "minutes": 5
  },
  {
    "slug": "2026-03-10",
    "title": "The Weights, Not the Source: What Meta Gave Away When It Released Llama",
    "titleZh": "Meta发布的是权重，不是源码",
    "cefr": "C2",
    "words": 511,
    "minutes": 7
  },
  {
    "slug": "2026-03-09",
    "title": "The Day Meta Gave Away a Model and Asked for Nothing Back",
    "titleZh": "Meta免费送出了一个模型",
    "cefr": "C1",
    "words": 451,
    "minutes": 6
  },
  {
    "slug": "2026-03-08",
    "title": "The Audience That Made the Salvo Legible",
    "titleZh": "那场进攻的真正受众是谁",
    "cefr": "C2",
    "words": 678,
    "minutes": 7
  },
  {
    "slug": "2026-03-07",
    "title": "The Night Iran Sent 300 Projectiles Toward Israel and Telephoned Ahead",
    "titleZh": "伊朗通知过后，发射了300枚",
    "cefr": "C1",
    "words": 541,
    "minutes": 7
  },
  {
    "slug": "2026-03-06",
    "title": "When the Justification Becomes the Evidence",
    "titleZh": "当辩护词变成了证据",
    "cefr": "C1",
    "words": 432,
    "minutes": 6
  },
  {
    "slug": "2026-03-05",
    "title": "The Day a Boy Genius Was Given Twenty-Five Years",
    "titleZh": "那个昔日天才被判了二十五年",
    "cefr": "B2",
    "words": 378,
    "minutes": 5
  },
  {
    "slug": "2026-03-04",
    "title": "The Last Hour Difficult to Photograph",
    "titleZh": "最后一种难以上传的体验",
    "cefr": "C2",
    "words": 654,
    "minutes": 8
  },
  {
    "slug": "2026-03-03",
    "title": "Four Minutes of Darkness, and the Three Economies It Produced",
    "titleZh": "四分钟黑暗的三种经济效应",
    "cefr": "C1",
    "words": 480,
    "minutes": 6
  },
  {
    "slug": "2026-03-02",
    "title": "The Two Minutes of Footage That Outran Three Months of Silence",
    "titleZh": "王妃消失期间，互联网在做什么",
    "cefr": "C1",
    "words": 531,
    "minutes": 7
  },
  {
    "slug": "2026-03-01",
    "title": "The Bench, the Trees, and the Two-Minute Video That Ended a Very Modern Rumour",
    "titleZh": "两分钟视频跑赢了三个月的沉默",
    "cefr": "B2",
    "words": 420,
    "minutes": 5
  },
  {
    "slug": "2026-02-28",
    "title": "The Quiet Wager: What Astera Labs' Listing Said About Where AI's Real Shortage Lies",
    "titleZh": "AI真正的短缺在连接层",
    "cefr": "C2",
    "words": 626,
    "minutes": 7
  },
  {
    "slug": "2026-02-27",
    "title": "The Company That Sells the Wires Behind the Boom",
    "titleZh": "卖数据中心连接线的公司上市",
    "cefr": "C1",
    "words": 452,
    "minutes": 6
  },
  {
    "slug": "2026-02-26",
    "title": "A Bridge Built for Smaller Ships: What the Patapsco Asked of Engineers Who Designed for a Lighter World",
    "titleZh": "为旧船建的桥遇上了新时代",
    "cefr": "C1",
    "words": 571,
    "minutes": 6
  },
  {
    "slug": "2026-02-25",
    "title": "A Loose Wire, a Drifting Ship, and the Bridge That Held a City Together",
    "titleZh": "一根电线与垮塌的那座桥",
    "cefr": "B2",
    "words": 412,
    "minutes": 5
  },
  {
    "slug": "2026-02-24",
    "title": "The Algorithm as Sovereign Territory: What the Order to Sell TikTok Has Already Decided",
    "titleZh": "算法作为主权领土",
    "cefr": "C2",
    "words": 686,
    "minutes": 8
  },
  {
    "slug": "2026-02-23",
    "title": "The Strange Physics of Ordering an Algorithm to Change Owners",
    "titleZh": "给一个算法下令换国籍",
    "cefr": "C1",
    "words": 478,
    "minutes": 6
  },
  {
    "slug": "2026-02-22",
    "title": "A Forum Goes Public, and Its Volunteers Quietly Become a Footnote",
    "titleZh": "Reddit上市，版主变成脚注",
    "cefr": "C1",
    "words": 503,
    "minutes": 6
  },
  {
    "slug": "2026-02-21",
    "title": "The Day a Forum Was Handed Its Own Ticker Symbol",
    "titleZh": "论坛拿到了自己的股票代码",
    "cefr": "B2",
    "words": 342,
    "minutes": 5
  },
  {
    "slug": "2026-02-20",
    "title": "The Ritual of the Foregone Conclusion: Reading 88 Percent and the Noon Hour",
    "titleZh": "正午排队者与87%的数字",
    "cefr": "C2",
    "words": 705,
    "minutes": 7
  },
  {
    "slug": "2026-02-19",
    "title": "A Number Was Required: Reading Putin's 88 Percent",
    "titleZh": "克里姆林宫需要那个数字",
    "cefr": "C1",
    "words": 513,
    "minutes": 6
  },
  {
    "slug": "2026-02-18",
    "title": "The Rocket That Means to Be Watched Failing",
    "titleZh": "那枚设计为公开失败的火箭",
    "cefr": "C2",
    "words": 574,
    "minutes": 7
  },
  {
    "slug": "2026-02-17",
    "title": "The Hour Starship Reached Space and Then Quietly Came Apart",
    "titleZh": "星舰飞到太空，然后悄悄解体了",
    "cefr": "C1",
    "words": 489,
    "minutes": 6
  },
  {
    "slug": "2026-02-16",
    "title": "A Second Oscar at 83, and the Question of When a Director Stops",
    "titleZh": "83岁，第二座奥斯卡，仍未停",
    "cefr": "B2",
    "words": 367,
    "minutes": 5
  },
  {
    "slug": "2026-02-15",
    "title": "A Director Wins an Oscar from His Drawing Desk",
    "titleZh": "宫崎骏在画桌前缺席领奖",
    "cefr": "B1",
    "words": 319,
    "minutes": 4
  },
  {
    "slug": "2026-02-14",
    "title": "The Long Way to the Front Row: How Cillian Murphy Got to Best Actor",
    "titleZh": "墨菲与诺兰之间的长期信任",
    "cefr": "B2",
    "words": 334,
    "minutes": 5
  },
  {
    "slug": "2026-02-13",
    "title": "A Cork Boy Steps Up: Cillian Murphy Wins Best Actor",
    "titleZh": "科克男孩走到了台前",
    "cefr": "B1",
    "words": 286,
    "minutes": 4
  },
  {
    "slug": "2026-02-12",
    "title": "The Long Wait, and What the Academy Was Really Voting For",
    "titleZh": "诺兰等了多久才拿到导演奖",
    "cefr": "B2",
    "words": 392,
    "minutes": 5
  },
  {
    "slug": "2026-02-11",
    "title": "How a Three-Hour Movie About a Physicist Swept the Oscars",
    "titleZh": "三小时物理学家电影横扫奥斯卡",
    "cefr": "B1",
    "words": 260,
    "minutes": 4
  },
  {
    "slug": "2026-02-10",
    "title": "The Long Boat Comes In: Sweden, Two Centuries of Neutrality, and the Day the Map Was Redrawn",
    "titleZh": "北欧老船驶入北约港口的那一天",
    "cefr": "C2",
    "words": 567,
    "minutes": 7
  },
  {
    "slug": "2026-02-09",
    "title": "A Country Edits the One Adjective It Had Lived By",
    "titleZh": "瑞典删掉了那个两百年的词",
    "cefr": "C1",
    "words": 471,
    "minutes": 6
  },
  {
    "slug": "2026-02-08",
    "title": "Haiku, Sonnet, Opus: What a Safety-First Lab Names Its Own Frontier",
    "titleZh": "俳句、十四行诗与史诗的命名",
    "cefr": "C2",
    "words": 542,
    "minutes": 7
  },
  {
    "slug": "2026-02-07",
    "title": "Three Names for One Bet: How Anthropic Sold Safety as Speed in March 2024",
    "titleZh": "Anthropic把安全包装成速度",
    "cefr": "C1",
    "words": 579,
    "minutes": 7
  },
  {
    "slug": "2026-02-06",
    "title": "The Small Case That Quietly Refused to Let an Airline Disown Its Own Chatbot",
    "titleZh": "航空公司拒绝认领自己的机器人",
    "cefr": "C2",
    "words": 558,
    "minutes": 7
  },
  {
    "slug": "2026-02-05",
    "title": "When the Help Window Becomes a Defendant",
    "titleZh": "当聊天机器人成为被告",
    "cefr": "C1",
    "words": 485,
    "minutes": 6
  },
  {
    "slug": "2026-02-04",
    "title": "The Quarter a Forum's Posts Showed Up on a Balance Sheet",
    "titleZh": "帖子变成营收的那个季度",
    "cefr": "C1",
    "words": 476,
    "minutes": 6
  },
  {
    "slug": "2026-02-03",
    "title": "What 'Soft Landing' Buys: A Sideways Lander and the Grammar of Public Contract",
    "titleZh": "「软着陆」在商业航天的新义",
    "cefr": "C2",
    "words": 467,
    "minutes": 7
  },
  {
    "slug": "2026-02-02",
    "title": "When a Forum Sold Its Conversations to a Search Engine",
    "titleZh": "论坛把用户对话卖给搜索引擎",
    "cefr": "B2",
    "words": 346,
    "minutes": 5
  },
  {
    "slug": "2026-02-01",
    "title": "After the Trace: What a Moving Image Owes the World",
    "titleZh": "当影像不再证明任何事曾发生过",
    "cefr": "C2",
    "words": 487,
    "minutes": 7
  },
  {
    "slug": "2026-01-31",
    "title": "Sideways on the Moon: How a Tipped-Over Lander Opened a New Lunar Ledger",
    "titleZh": "侧躺在月球上的商业登月新账本",
    "cefr": "C1",
    "words": 500,
    "minutes": 6
  },
  {
    "slug": "2026-01-30",
    "title": "A Man Who Knew the Price: Reading Navalny Two Years On",
    "titleZh": "他知道代价，还是回去了",
    "cefr": "C2",
    "words": 630,
    "minutes": 7
  },
  {
    "slug": "2026-01-29",
    "title": "The Widow Who Inherited a Movement She Had Not Asked For",
    "titleZh": "她继承了一场她从未索取的运动",
    "cefr": "C1",
    "words": 482,
    "minutes": 6
  },
  {
    "slug": "2026-01-28",
    "title": "A Million Tokens of Memory, and the Quiet Argument Underneath",
    "titleZh": "百万token与记忆的哲学追问",
    "cefr": "C2",
    "words": 547,
    "minutes": 7
  },
  {
    "slug": "2026-01-27",
    "title": "The Quiet Day a Model Was First Asked to Read a Whole Novel at Once",
    "titleZh": "第一次被要求一口气读完长篇",
    "cefr": "C1",
    "words": 446,
    "minutes": 6
  },
  {
    "slug": "2026-01-26",
    "title": "The Lander That Hit Its Mark and Tipped Over",
    "titleZh": "倒立在月球上的精准降落",
    "cefr": "C2",
    "words": 585,
    "minutes": 7
  },
  {
    "slug": "2026-01-25",
    "title": "The Minute of Footage That Made a Studio Mogul Pause Construction",
    "titleZh": "一段视频让制片厂暂停施工",
    "cefr": "C1",
    "words": 484,
    "minutes": 6
  },
  {
    "slug": "2026-01-24",
    "title": "A Three-Yard Pass, a Pop Star, and a Word Football Forgot: Reading Super Bowl LVIII",
    "titleZh": "传球、明星与超级碗的王朝",
    "cefr": "B2",
    "words": 430,
    "minutes": 5
  },
  {
    "slug": "2026-01-23",
    "title": "The Football Final That Became a Love Story",
    "titleZh": "超级碗变成了一段爱情故事",
    "cefr": "B1",
    "words": 322,
    "minutes": 4
  },
  {
    "slug": "2026-01-22",
    "title": "A Planet Begins to Read Its Own Handwriting",
    "titleZh": "一颗星球开始读懂自己的笔迹",
    "cefr": "C2",
    "words": 546,
    "minutes": 7
  },
  {
    "slug": "2026-01-21",
    "title": "A Slow Subtraction: What 1,111 Days Above the Earth Make of a Body",
    "titleZh": "在太空1111天后的身体",
    "cefr": "C2",
    "words": 587,
    "minutes": 7
  },
  {
    "slug": "2026-01-20",
    "title": "What Apple Could Not Buy with Three Billion Dollars",
    "titleZh": "苹果用三十亿美元买不到的东西",
    "cefr": "C1",
    "words": 478,
    "minutes": 6
  },
  {
    "slug": "2026-01-19",
    "title": "The Satellite That Reads the Ocean by the Color It Refuses to Show",
    "titleZh": "通过颜色拒绝来读海洋的卫星",
    "cefr": "C1",
    "words": 497,
    "minutes": 6
  },
  {
    "slug": "2026-01-18",
    "title": "The Two Songs Country Music Played for Toby Keith",
    "titleZh": "乡村音乐给他放了两首歌",
    "cefr": "B2",
    "words": 358,
    "minutes": 5
  },
  {
    "slug": "2026-01-17",
    "title": "The Cowboy Who Sang for Soldiers",
    "titleZh": "从油田唱到军营的乡村歌手",
    "cefr": "B1",
    "words": 290,
    "minutes": 4
  },
  {
    "slug": "2026-01-16",
    "title": "The Actress Who Got Famous for What She Could Not Do",
    "titleZh": "因为做不到某件事而成名的演员",
    "cefr": "B2",
    "words": 473,
    "minutes": 5
  },
  {
    "slug": "2026-01-15",
    "title": "The Cosmonaut Who Counted His Days From Above and Below",
    "titleZh": "在太空数日子的宇航员",
    "cefr": "C1",
    "words": 431,
    "minutes": 6
  },
  {
    "slug": "2026-01-14",
    "title": "What the Vision Pro Was Actually Selling: A Quiet Lesson in Two-Sided Markets",
    "titleZh": "Vision Pro与双边市场的冷账",
    "cefr": "C1",
    "words": 462,
    "minutes": 6
  },
  {
    "slug": "2026-01-13",
    "title": "The Headset That Tim Cook Wanted Us to Love",
    "titleZh": "苹果头显与现实相遇的那一刻",
    "cefr": "B2",
    "words": 391,
    "minutes": 5
  },
  {
    "slug": "2026-01-12",
    "title": "When the Render Did Not Match the Room",
    "titleZh": "渲染图与现场之间的那道缝",
    "cefr": "B2",
    "words": 445,
    "minutes": 5
  },
  {
    "slug": "2026-01-11",
    "title": "The Day a Magical Chocolate World Turned Out to Be a Bouncy Castle",
    "titleZh": "巧克力奇境其实是充气城堡",
    "cefr": "B1",
    "words": 298,
    "minutes": 4
  },
  {
    "slug": "2026-01-10",
    "title": "The Voice Sondheim Wrote Around, and the Song That Outlived the Career",
    "titleZh": "桑德海姆为限制而作的歌",
    "cefr": "B2",
    "words": 401,
    "minutes": 5
  },
  {
    "slug": "2026-01-09",
    "title": "The Voice That Was Too Small for Long Notes, and Just Right for One Song",
    "titleZh": "声音不够大，写出了那首歌",
    "cefr": "B1",
    "words": 287,
    "minutes": 4
  },
  {
    "slug": "2026-01-08",
    "title": "How a Word That Used to Mean \"Plain to See\" Came to Mean \"Pull It Toward You\"",
    "titleZh": "一个动词是怎么换了工作的",
    "cefr": "B2",
    "words": 372,
    "minutes": 5
  },
  {
    "slug": "2026-01-07",
    "title": "The Year a Self-Help Verb Climbed Out of TikTok",
    "titleZh": "「显现」这个词爬出了TikTok",
    "cefr": "B1",
    "words": 297,
    "minutes": 4
  },
  {
    "slug": "2026-01-06",
    "title": "The Moon Sniper That Landed on Its Nose",
    "titleZh": "「月球狙击手」落地后倒了",
    "cefr": "C1",
    "words": 478,
    "minutes": 6
  },
  {
    "slug": "2026-01-05",
    "title": "The Lander That Nailed Its Mark and Then Fell Over",
    "titleZh": "降落精准，然后侧翻在月球上",
    "cefr": "C1",
    "words": 480,
    "minutes": 6
  },
  {
    "slug": "2026-01-04",
    "title": "Private Orbit: What a Flag Means When the Seat Has an Invoice",
    "titleZh": "国旗与发票：私人轨道的象征",
    "cefr": "C2",
    "words": 503,
    "minutes": 7
  },
  {
    "slug": "2026-01-03",
    "title": "When a Country Buys a Seat to Orbit: Reading the Ax-3 Mission",
    "titleZh": "一个国家租了一个轨道座位",
    "cefr": "C1",
    "words": 521,
    "minutes": 6
  },
  {
    "slug": "2026-01-02",
    "title": "The Caucus as Liturgy: Subzero Iowa and a Party Already Closed",
    "titleZh": "党团会议作为一场确认仪式",
    "cefr": "C2",
    "words": 735,
    "minutes": 8
  },
  {
    "slug": "2026-01-01",
    "title": "How a Subzero Night in Iowa Settled a Race That Was Already Settling",
    "titleZh": "爱荷华寒夜再次确认了胜局",
    "cefr": "C1",
    "words": 435,
    "minutes": 6
  },
  {
    "slug": "2025-12-31",
    "title": "On Borrowed Voices: The Public University in the Age of Licensed Cognition",
    "titleZh": "公立大学租用语言的那纸合同",
    "cefr": "C2",
    "words": 538,
    "minutes": 7
  },
  {
    "slug": "2025-12-30",
    "title": "When a Public University Decided to Hand a Chatbot the Keys to Freshman Comp",
    "titleZh": "亚利桑那把写作课交给了AI",
    "cefr": "C1",
    "words": 510,
    "minutes": 6
  },
  {
    "slug": "2025-12-29",
    "title": "A Mandate to Stay Where You Are: Taiwan, the Status Quo, and the Question Nobody Wants Settled",
    "titleZh": "选了一位维持现状的总统",
    "cefr": "C2",
    "words": 591,
    "minutes": 7
  },
  {
    "slug": "2025-12-28",
    "title": "A Third Term, a Hung Parliament, and the Hour After the Vote",
    "titleZh": "赖清德的悬空授权",
    "cefr": "C1",
    "words": 461,
    "minutes": 6
  },
  {
    "slug": "2025-12-27",
    "title": "The First Commercial Failure on the Way to the Moon: Peregrine and the Privatization of an Old Frontier",
    "titleZh": "商业登月首败与月球经济",
    "cefr": "C2",
    "words": 679,
    "minutes": 7
  },
  {
    "slug": "2025-12-26",
    "title": "What Failed Above the Pacific Was Not Quite the Mission",
    "titleZh": "那次「失败」登月并不算失败",
    "cefr": "C1",
    "words": 556,
    "minutes": 6
  },
  {
    "slug": "2025-12-25",
    "title": "The Arithmetic of a Cleaner Ocean",
    "titleZh": "清塑料的账本缺了一半成本",
    "cefr": "C1",
    "words": 499,
    "minutes": 6
  },
  {
    "slug": "2025-12-24",
    "title": "A Good Year for the Plastic Catchers, and the Old Question They Cannot Answer",
    "titleZh": "捞了十年，问题还是那个问题",
    "cefr": "B2",
    "words": 418,
    "minutes": 5
  },
  {
    "slug": "2025-12-23",
    "title": "The Drained Lake That Refuses to Stay Buried",
    "titleZh": "五百年后，湖底的缓慢复仇",
    "cefr": "C1",
    "words": 499,
    "minutes": 6
  },
  {
    "slug": "2025-12-22",
    "title": "A Capital That Drinks the Ground It Stands On",
    "titleZh": "一座城市正在喝干它脚下的地层",
    "cefr": "B2",
    "words": 419,
    "minutes": 5
  },
  {
    "slug": "2025-12-21",
    "title": "Whose Friday? Reading the Four-Day Week Through Its Footnotes",
    "titleZh": "谁的周五：工时改革的漏洞",
    "cefr": "C1",
    "words": 498,
    "minutes": 6
  },
  {
    "slug": "2025-12-20",
    "title": "A Quieter Working Week Is Already Reshaping European Offices",
    "titleZh": "四天工作制悄悄进入欧洲",
    "cefr": "B2",
    "words": 405,
    "minutes": 5
  },
  {
    "slug": "2025-12-19",
    "title": "A Town the State Bought: What \"Routine\" Means When the Earth Sets the Calendar",
    "titleZh": "政府买下了那座小镇",
    "cefr": "C1",
    "words": 524,
    "minutes": 7
  },
  {
    "slug": "2025-12-18",
    "title": "The Town That Learned to Read Its Volcano",
    "titleZh": "与火山为邻的格林达维克",
    "cefr": "B2",
    "words": 392,
    "minutes": 5
  },
  {
    "slug": "2025-12-17",
    "title": "The Cathedral That Refused to Become Anyone's Statement",
    "titleZh": "法国选择原样重建的政治含义",
    "cefr": "C1",
    "words": 535,
    "minutes": 6
  },
  {
    "slug": "2025-12-16",
    "title": "How a Cathedral Came Back on Schedule",
    "titleZh": "圣母院按时重开了",
    "cefr": "B2",
    "words": 418,
    "minutes": 5
  },
  {
    "slug": "2025-12-15",
    "title": "The Ladder That Keeps Crowning Finland",
    "titleZh": "那把一直把芬兰排第一的梯子",
    "cefr": "C1",
    "words": 480,
    "minutes": 6
  },
  {
    "slug": "2025-12-14",
    "title": "Why the Happiest Country Is Quietly Embarrassed by the Title",
    "titleZh": "芬兰为快乐第一感到尴尬",
    "cefr": "B2",
    "words": 391,
    "minutes": 5
  },
  {
    "slug": "2025-12-13",
    "title": "What Nepal Is Really Selling When It Raises the Price of Everest",
    "titleZh": "尼泊尔卖的究竟是什么",
    "cefr": "C1",
    "words": 451,
    "minutes": 6
  },
  {
    "slug": "2025-12-12",
    "title": "A New Price Tag on the Top of the World",
    "titleZh": "珠穆朗玛峰许可证涨价之后",
    "cefr": "B2",
    "words": 417,
    "minutes": 5
  },
  {
    "slug": "2025-12-11",
    "title": "One Receptor, Several Specialities, and a Quiet Argument About What Counts as a Cure",
    "titleZh": "一个受体，横跨五个医学专科",
    "cefr": "C2",
    "words": 487,
    "minutes": 7
  },
  {
    "slug": "2025-12-10",
    "title": "A Drug Class That Keeps Discovering New Things About Itself",
    "titleZh": "一类药物不断发现新用途",
    "cefr": "C1",
    "words": 457,
    "minutes": 6
  },
  {
    "slug": "2025-12-09",
    "title": "A Cruelty We Are Not Sure How to Recognize",
    "titleZh": "一道无法被确认的伤害",
    "cefr": "C2",
    "words": 539,
    "minutes": 7
  },
  {
    "slug": "2025-12-08",
    "title": "The Case Against Farming an Animal We Are Still Trying to Understand",
    "titleZh": "饲养一种我们尚未读懂的动物",
    "cefr": "C1",
    "words": 432,
    "minutes": 6
  },
  {
    "slug": "2025-12-07",
    "title": "The Long Whitening: A Reef That Is Going, Not Gone",
    "titleZh": "珊瑚礁的漫长白化：正在消失中",
    "cefr": "C2",
    "words": 588,
    "minutes": 7
  },
  {
    "slug": "2025-12-06",
    "title": "When the Warning Scale Itself Had to Be Rebuilt",
    "titleZh": "当预警量表走到了刻度尽头",
    "cefr": "C1",
    "words": 451,
    "minutes": 6
  },
  {
    "slug": "2025-12-05",
    "title": "Borrowed Customers: What Japan's Tourism Record Is Really Counting",
    "titleZh": "用人口萎缩换旅游繁荣的代价",
    "cefr": "C1",
    "words": 496,
    "minutes": 6
  },
  {
    "slug": "2025-12-04",
    "title": "A Cheap Yen, a Crowded Country: How 36.9 Million Visitors Found Japan",
    "titleZh": "日元弱，近4000万人涌日本",
    "cefr": "B2",
    "words": 432,
    "minutes": 5
  },
  {
    "slug": "2025-12-03",
    "title": "A Big Majority on a Small Vote: The Curious Shape of Labour's 2024 Win",
    "titleZh": "工党的大胜建立在小票仓之上",
    "cefr": "C2",
    "words": 566,
    "minutes": 7
  },
  {
    "slug": "2025-12-02",
    "title": "A Country That Voted Tired",
    "titleZh": "一个投票投到疲倦的国家",
    "cefr": "C1",
    "words": 468,
    "minutes": 6
  },
  {
    "slug": "2025-12-01",
    "title": "The Mandate That Refused to Be Coronated",
    "titleZh": "那个拒绝被加冕的选举结果",
    "cefr": "C2",
    "words": 643,
    "minutes": 7
  },
  {
    "slug": "2025-11-30",
    "title": "What the World's Largest Vote Actually Said",
    "titleZh": "六亿张选票实际说了什么",
    "cefr": "C1",
    "words": 441,
    "minutes": 6
  },
  {
    "slug": "2025-11-29",
    "title": "What a Number Owes: The Baku Climate Deal and the Arithmetic of an Older Debt",
    "titleZh": "巴库气候债：三千亿与那笔旧账",
    "cefr": "C2",
    "words": 543,
    "minutes": 7
  },
  {
    "slug": "2025-11-28",
    "title": "The Gavel Fell Before the Number Could Be Argued With",
    "titleZh": "槌声落下时，数字还没谈完",
    "cefr": "C1",
    "words": 519,
    "minutes": 6
  },
  {
    "slug": "2025-11-27",
    "title": "A Statute for a Moving Target: The EU AI Act and the Old Question of How Law Catches Up",
    "titleZh": "一部追赶移动靶的法律赌注",
    "cefr": "C2",
    "words": 593,
    "minutes": 7
  },
  {
    "slug": "2025-11-26",
    "title": "The World's First AI Law Is Already Being Bent Out of Shape",
    "titleZh": "世界上第一部AI法已在被弯曲",
    "cefr": "C1",
    "words": 469,
    "minutes": 6
  },
  {
    "slug": "2025-11-25",
    "title": "The Quiet Question Every Essay Now Carries",
    "titleZh": "每篇文章背后那个沉默的问题",
    "cefr": "C2",
    "words": 554,
    "minutes": 7
  },
  {
    "slug": "2025-11-24",
    "title": "After Two Years of ChatGPT, Professors Stopped Trying to Catch Their Students",
    "titleZh": "教授们停止了追查，转而妥协",
    "cefr": "C1",
    "words": 478,
    "minutes": 6
  },
  {
    "slug": "2025-11-23",
    "title": "A Number That Reads Like a Verdict: Six Figures and the Soul of the American Degree",
    "titleZh": "十万美元学费衡量了什么",
    "cefr": "C2",
    "words": 589,
    "minutes": 7
  },
  {
    "slug": "2025-11-22",
    "title": "When the Bill Says Six Figures: What a $100,000 College Sticker Actually Measures",
    "titleZh": "十万美元学费牌价衡量了什么",
    "cefr": "C1",
    "words": 433,
    "minutes": 6
  },
  {
    "slug": "2025-11-21",
    "title": "The Visa That Quietly Pays the British University",
    "titleZh": "毕业签证悄悄撑着大学财务",
    "cefr": "C1",
    "words": 479,
    "minutes": 6
  },
  {
    "slug": "2025-11-20",
    "title": "Why Britain Decided Not to Close a Door It Had Just Opened",
    "titleZh": "英国为何决定不关这扇刚开的门",
    "cefr": "B2",
    "words": 343,
    "minutes": 5
  },
  {
    "slug": "2025-11-19",
    "title": "What Canada's Student Cap Revealed About a Funding Model Nobody Wanted to Name",
    "titleZh": "加拿大学签上限揭开了一种默契",
    "cefr": "C1",
    "words": 456,
    "minutes": 6
  },
  {
    "slug": "2025-11-18",
    "title": "When Ottawa Cut the Number, Small Towns Felt It First",
    "titleZh": "渥太华削配额，小镇先感受",
    "cefr": "B2",
    "words": 421,
    "minutes": 5
  },
  {
    "slug": "2025-11-17",
    "title": "The Cap That Was Not About Students",
    "titleZh": "留学名额上限不是为学生",
    "cefr": "C1",
    "words": 479,
    "minutes": 6
  },
  {
    "slug": "2025-11-16",
    "title": "On the Slow Moral Weather of a Laboratory",
    "titleZh": "一所大实验室的慢速道德气候",
    "cefr": "C2",
    "words": 656,
    "minutes": 7
  },
  {
    "slug": "2025-11-15",
    "title": "The Quiet Machinery That Failed at Stanford",
    "titleZh": "大实验室自我监管的失败",
    "cefr": "C1",
    "words": 451,
    "minutes": 6
  },
  {
    "slug": "2025-11-14",
    "title": "The Pyrrhic Picket: What Hollywood Won, and What It Has Lost",
    "titleZh": "历史性合同与消失的编剧室",
    "cefr": "C2",
    "words": 529,
    "minutes": 7
  },
  {
    "slug": "2025-11-13",
    "title": "Hollywood Won Its Strike. Then the Jobs Disappeared.",
    "titleZh": "好莱坞赢了罢工，失去了工作",
    "cefr": "C1",
    "words": 518,
    "minutes": 6
  },
  {
    "slug": "2025-11-12",
    "title": "The Painting That Was Never the Point: What the Soup Was Really Aimed At",
    "titleZh": "那碗汤的真正目标不是那幅画",
    "cefr": "C1",
    "words": 483,
    "minutes": 6
  },
  {
    "slug": "2025-11-11",
    "title": "How a Vertical Video Feed Became Publishing's New Acquisitions Desk",
    "titleZh": "竖屏视频成了出版业的选题编辑",
    "cefr": "C1",
    "words": 452,
    "minutes": 6
  },
  {
    "slug": "2025-11-10",
    "title": "How a Hashtag on TikTok Started Choosing What Bookshops Sell",
    "titleZh": "TikTok书单重塑了书店货架",
    "cefr": "B2",
    "words": 378,
    "minutes": 5
  },
  {
    "slug": "2025-11-09",
    "title": "When a Country Treats Its Opening Ceremony Like a Manifesto",
    "titleZh": "开幕式作为一份国家宣言",
    "cefr": "B2",
    "words": 369,
    "minutes": 5
  },
  {
    "slug": "2025-11-08",
    "title": "What a Two-Billion-Dollar Concert Tour Can and Cannot Do",
    "titleZh": "两百亿美元巡演能与不能做的事",
    "cefr": "B2",
    "words": 428,
    "minutes": 5
  },
  {
    "slug": "2025-11-07",
    "title": "The Economics of a Truck That Disappeared on Its Way to Easter",
    "titleZh": "一辆巧克力货车与供应链经济学",
    "cefr": "C1",
    "words": 486,
    "minutes": 6
  },
  {
    "slug": "2025-11-06",
    "title": "A Voice Returned: How Machine Learning Read a Scroll Buried by Vesuvius",
    "titleZh": "机器学习读出烧焦的卷轴",
    "cefr": "C2",
    "words": 550,
    "minutes": 7
  },
  {
    "slug": "2025-11-05",
    "title": "How Paris Rebuilt Notre-Dame Using 13th-Century Tools",
    "titleZh": "巴黎用古法修好了圣母院",
    "cefr": "B1",
    "words": 300,
    "minutes": 4
  },
  {
    "slug": "2025-11-04",
    "title": "India Voted for Six Weeks. The Answer Was Quieter Than Anyone Predicted.",
    "titleZh": "莫迪赢了，但赢得比预期更安静",
    "cefr": "B2",
    "words": 413,
    "minutes": 5
  },
  {
    "slug": "2025-11-03",
    "title": "A Landslide Built on a Thin Slice of the Electorate",
    "titleZh": "工党以最小票仓赢得最大多数席",
    "cefr": "B2",
    "words": 341,
    "minutes": 5
  },
  {
    "slug": "2025-11-02",
    "title": "Australia Picks a Number, and a Generation of Students Waits to Hear Theirs",
    "titleZh": "澳大利亚限额之后的漫长等待",
    "cefr": "B2",
    "words": 416,
    "minutes": 5
  },
  {
    "slug": "2025-11-01",
    "title": "When a University President Could No Longer Stand by His Own Papers",
    "titleZh": "斯坦福校长的论文危机",
    "cefr": "B2",
    "words": 403,
    "minutes": 5
  },
  {
    "slug": "2025-10-31",
    "title": "Soup, Glass, and the Mona Lisa: A Protest the Painting Could Not Feel",
    "titleZh": "泼向蒙娜丽莎的那碗南瓜汤",
    "cefr": "B2",
    "words": 388,
    "minutes": 5
  },
  {
    "slug": "2025-10-30",
    "title": "The Night the Olympics Left the Stadium and Sailed Down a River",
    "titleZh": "奥运会漂浮在塞纳河上的那夜",
    "cefr": "B1",
    "words": 349,
    "minutes": 4
  },
  {
    "slug": "2025-10-29",
    "title": "When One Singer Becomes a Small Economy",
    "titleZh": "一位歌手变成了一套经济体",
    "cefr": "B1",
    "words": 294,
    "minutes": 4
  },
  {
    "slug": "2025-10-28",
    "title": "How a Truckload of KitKats Disappeared, and What That Says About the Snack Aisle",
    "titleZh": "当零食成为货运犯罪的目标",
    "cefr": "B2",
    "words": 396,
    "minutes": 5
  },
  {
    "slug": "2025-10-27",
    "title": "How a Truck Full of KitKats Vanished on Its Way to Easter",
    "titleZh": "复活节前夕消失的巧克力车",
    "cefr": "B1",
    "words": 290,
    "minutes": 4
  },
  {
    "slug": "2025-10-26",
    "title": "How Three Students Read a Scroll No One Had Opened in 2,000 Years",
    "titleZh": "三名学生读开了两千年的纸卷",
    "cefr": "B2",
    "words": 386,
    "minutes": 5
  },
  {
    "slug": "2025-10-25",
    "title": "A Library That Survived Because It Burned",
    "titleZh": "被火焰保存的图书馆",
    "cefr": "C1",
    "words": 463,
    "minutes": 6
  },
  {
    "slug": "2025-10-24",
    "title": "One Night in Berlin: Spain Wins a Record Fourth Euro Title",
    "titleZh": "柏林决赛夜，西班牙封王",
    "cefr": "B1",
    "words": 305,
    "minutes": 4
  },
  {
    "slug": "2025-10-23",
    "title": "Spain's Euro 2024 Win Was About More Than a Trophy",
    "titleZh": "西班牙夺冠背后的身份重建",
    "cefr": "B2",
    "words": 418,
    "minutes": 5
  },
  {
    "slug": "2025-10-22",
    "title": "The Teenager Who Rewrote the Record Books at Euro 2024",
    "titleZh": "十六岁的欧洲杯历史",
    "cefr": "B1",
    "words": 298,
    "minutes": 4
  },
  {
    "slug": "2025-10-21",
    "title": "The Boy from La Masia Who Rewrote the Record Books",
    "titleZh": "青训流水线上的最年轻",
    "cefr": "B2",
    "words": 398,
    "minutes": 5
  },
  {
    "slug": "2025-10-20",
    "title": "The Comedian Who Let Silence Do the Talking",
    "titleZh": "用沉默说笑的喜剧人",
    "cefr": "B1",
    "words": 255,
    "minutes": 4
  },
  {
    "slug": "2025-10-19",
    "title": "The Man Who Made Silence Funny",
    "titleZh": "用沉默说笑话的人",
    "cefr": "B2",
    "words": 408,
    "minutes": 4
  },
  {
    "slug": "2025-10-18",
    "title": "The 25 Days That Pushed Biden Out",
    "titleZh": "党内的三周倒计时",
    "cefr": "C1",
    "words": 499,
    "minutes": 6
  },
  {
    "slug": "2025-10-17",
    "title": "The Rarest Move in Democratic Politics: Choosing to Step Aside",
    "titleZh": "主动让权的总统有多稀少",
    "cefr": "C2",
    "words": 527,
    "minutes": 7
  },
  {
    "slug": "2025-10-16",
    "title": "The 107-Day Campaign That Rewrote the Rulebook",
    "titleZh": "百日闪电战的选举逻辑",
    "cefr": "C1",
    "words": 456,
    "minutes": 6
  },
  {
    "slug": "2025-10-15",
    "title": "The Fastest Coronation in Modern Politics: What Harris's Rise Revealed",
    "titleZh": "速度即合法性的一次加冕",
    "cefr": "C2",
    "words": 528,
    "minutes": 7
  },
  {
    "slug": "2025-10-14",
    "title": "France's AI Darling Signs a Deal That Embarrasses Its Own Story",
    "titleZh": "法国AI独角兽的矛盾时刻",
    "cefr": "C1",
    "words": 452,
    "minutes": 6
  },
  {
    "slug": "2025-10-13",
    "title": "The Sovereign AI That Launched on Someone Else's Cloud",
    "titleZh": "主权模型，借来的算力",
    "cefr": "C2",
    "words": 527,
    "minutes": 7
  },
  {
    "slug": "2025-10-12",
    "title": "The Rugby Player Who Rewrote What an Olympian Looks Like",
    "titleZh": "橄榄球运动员重写了奥运身材的定义",
    "cefr": "B1",
    "words": 303,
    "minutes": 4
  },
  {
    "slug": "2025-10-11",
    "title": "The Athlete Who Carried a Sport on Her Phone",
    "titleZh": "她用手机扛起了一项运动",
    "cefr": "B2",
    "words": 408,
    "minutes": 5
  },
  {
    "slug": "2025-10-10",
    "title": "The Night Léon Marchand Won Two Gold Medals in Two Hours",
    "titleZh": "两小时两枚金牌的那个夜晚",
    "cefr": "B1",
    "words": 302,
    "minutes": 4
  },
  {
    "slug": "2025-10-09",
    "title": "The Coach Who Made Two Champions: Inside Léon Marchand's Paris Sweep",
    "titleZh": "法国终于有了自己的泳坛偶像",
    "cefr": "B2",
    "words": 332,
    "minutes": 5
  },
  {
    "slug": "2025-10-08",
    "title": "The Shooter Who Won Silver With One Hand in His Pocket",
    "titleZh": "口袋里的那只手",
    "cefr": "B1",
    "words": 296,
    "minutes": 4
  },
  {
    "slug": "2025-10-07",
    "title": "The Man Who Won Silver With His Hand in His Pocket",
    "titleZh": "把手揣进口袋的奥运亚军",
    "cefr": "B2",
    "words": 398,
    "minutes": 5
  }
];
