/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#dbe4e7',
        'on-surface-variant': '#586064',
        'primary-fixed-dim': '#a2e2c8',
        'outline-variant': '#abb3b7',
        'primary': '#042f24',
        'tertiary': '#566445',
        'tertiary-dim': '#4a5739',
        'surface-bright': '#f8f9fa',
        'on-primary-fixed-variant': '#286652',
        'tertiary-fixed': '#e4f4cc',
        'primary-container': '#b0f0d6',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#d9e3f4',
        'surface': '#f8f9fa',
        'on-tertiary-container': '#4f5d3e',
        'surface-variant': '#dbe4e7',
        'inverse-on-surface': '#9b9d9e',
        'on-primary-fixed': '#004936',
        'error-dim': '#4e0309',
        'secondary-fixed': '#d9e3f4',
        'background': '#f8f9fa',
        'on-tertiary': '#efffd6',
        'tertiary-fixed-dim': '#d6e5be',
        'primary-dim': '#021a14',
        'on-secondary-fixed-variant': '#525c6a',
        'secondary-dim': '#4a5462',
        'on-error': '#fff7f6',
        'secondary': '#56606e',
        'secondary-fixed-dim': '#cbd5e6',
        'surface-container-high': '#e2e9ec',
        'outline': '#737c7f',
        'on-primary-container': '#1c5c48',
        'on-tertiary-fixed-variant': '#596748',
        'error': '#9f403d',
        'on-primary': '#ffffff',
        'surface-container': '#eaeff1',
        'on-secondary-container': '#485260',
        'on-error-container': '#752121',
        'tertiary-container': '#e4f4cc',
        'surface-tint': '#042f24',
        'inverse-primary': '#b8f9de',
        'on-tertiary-fixed': '#3d4a2e',
        'error-container': '#fe8983',
        'on-secondary': '#f7f9ff',
        'primary-fixed': '#b0f0d6',
        'on-surface': '#042f24',
        'on-background': '#042f24',
        'surface-container-low': '#f1f4f6',
        'inverse-surface': '#0c0f10',
        'surface-dim': '#d1dce0',
        'on-secondary-fixed': '#36404d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
  ],
};
